### ISSUE TITLE
Image Code

### ISSUE THREAD

**Issue by emresaracoglu** [stefangabos/Zebra_Tooltips#11]
Hello

I like it this tooltip app, thank you! I have a question. How I can run HTML codes in the tooltip?

For example; I want to add image code in the tooltip, it is possible for Zebra_Tooltips?

**Comment by Thanushkajayasinghe** [comment]
check this link:-

https://jsfiddle.net/x5rwbdmc/

**Comment by emresaracoglu** [comment]
Thank you @Thanushkajayasinghe !
