### ISSUE TITLE
Options parameter never used

### ISSUE THREAD

**Issue by gfinocchiaro** [stefangabos/Zebra_Tooltips#16]
Looking at the source code, it seems that the 'options' parameter passed to the constructor actually is never used.

**Comment by stefangabos** [comment]
...then none of the examples would work...

**Comment by stefangabos** [comment]
wait you are right! hmmm, indeed that argument is not being used

**Comment by stefangabos** [comment]
should work now. thanks for reporting this!

**Comment by gfinocchiaro** [comment]
👍
