### ISSUE TITLE
making tips work for elements added to the dom via ajax

### ISSUE THREAD

**Issue by arkid** [stefangabos/Zebra_Tooltips#17]
What is the most efficient way to handle this, the plugin is definitely working but for various content I have being injected into the DOM after page load it won't work.   How can I keep zebra tooltips refreshed to handle this ?

**Comment by stefangabos** [comment]
calling 
`new $.Zebra_Tooltips(new_elements)`

**Comment by stefangabos** [comment]
...assuming you `know` when and what are those elements that are dynamically being added to the page...

**Comment by arkid** [comment]
Ok... so to be sure, there isn't a refresh type method that can just review the original declaration and look for all matching classes/elements again ?

**Comment by stefangabos** [comment]
no, there isn't...

**Comment by arkid** [comment]
Ok thanks for clarification and the help!

**Comment by stefangabos** [comment]
you're welcome!
