### ISSUE TITLE
Zebra ToolTip Resize Error

### ISSUE THREAD

**Issue by sgkdnay** [stefangabos/Zebra_Tooltips#2]
Always get this error when resizing any browser. Using JQuery 2.x.x

Uncaught TypeError: Cannot set property 'window_resized' of undefined Zebra_ToolTips.js:1
(anonymous function) Zebra_ToolTips.js:1
x.extend.each jquery-2.0.3.min.js:4
x.fn.x.each jquery-2.0.3.min.js:4
(anonymous function) Zebra_ToolTips.js:1
x.event.dispatch jquery-2.0.3.min.js:5
y.handle jquery-2.0.3.min.js:5

**Comment by LuisFernando10** [comment]
I also have this error, has anyone been able to solve it?

![image](https://user-images.githubusercontent.com/46758736/96899671-cdf41300-1456-11eb-8b3c-5fa693db6a29.png)
