### ISSUE TITLE
The tooltip is not dynamic in a list of items

### ISSUE THREAD

**Issue by Hervera** [stefangabos/Zebra_Tooltips#28]
The tooltip gives the same title when they are different titles in a group of items. It should have a dynamic id for each item that is within an array.

**Comment by stefangabos** [comment]
ok, i will look into it. thank you for reporting!

**Comment by stefangabos** [comment]
i am not able to reproduce this.
i tried with

```html
<a href="javascript: void(0)" class="tooltip" title="title 1">Sample tooltip 1</a>
<a href="javascript: void(0)" class="tooltip" title="title 2">Sample tooltip 2</a>
<a href="javascript: void(0)" class="tooltip" title="title 3">Sample tooltip 3</a>
```
and also with
```html
<a href="javascript: void(0)" class="tooltip" data-ztt_content="title 1">Sample tooltip 1</a>
<a href="javascript: void(0)" class="tooltip" data-ztt_content="title 2">Sample tooltip 2</a>
<a href="javascript: void(0)" class="tooltip" data-ztt_content="title 3">Sample tooltip 3</a>
```

```js
new $.Zebra_Tooltips($('.tooltip'));
```
and i got the expected results both time. 
can you please show me how are you doing it?

**Comment by Hervera** [comment]
All the tooltips are getting the same tiitle, which is the title of the last item! Look at this [demo](https://jsfiddle.net/Hervera/4hn0dfou/4/)

**Comment by stefangabos** [comment]
you are using the previous version, where this was indeed a bug.
use 2.10 instead of 2.0.5

**Comment by Hervera** [comment]
finely, it works with version 2.1.0
