### ISSUE TITLE
Zebra Tooltip [Error scroll resize]

### ISSUE THREAD

**Issue by LuisFernando10** [stefangabos/Zebra_Tooltips#32]
I have started to use this library, but I have realized that they have a bug when scrolling and when, for example, removing a `<tr>` from a `<table>`, it loses the reference of that HTML and the Tooltips go haywire.

To tell the truth I don't know if it is caused by the dislike of JQuery or it is already an internal problem of the library, I use JQuery3.5

This is my error:

`g(window).bind("scroll resize",function(b){j.each(function(){var a=g(this).data("Zebra_Tooltip");"scroll"==b.type?a.window_scrolled= !0:a.window_resized=!0;g(this).data("Zebra_Tooltip",a)})})}})(jQuery);`

![image](https://user-images.githubusercontent.com/46758736/96900870-31327500-1458-11eb-824d-9c61d64f34f4.png)

**Comment by stefangabos** [comment]
that code is not part of the library. if you can create a jsfiddle example for me i'd be happy to help
