### ISSUE TITLE
Title content is deleted after loaded?

### ISSUE THREAD

**Issue by viirak** [stefangabos/Zebra_Tooltips#4]
In my case I implement tooltip on elements loaded via ajax. so on every success,
new $.Zebra_Tooltips($('.item'),{'animation_speed':150});

first page of ajax loaded is fine. but from second page will make first page tooltip fail because content of title attribute was deleted.

Why you need to deleted?

**Comment by stefangabos** [comment]
This is now fixed. Thanks!
